"""Container build: turn a self-contained project into a deployable image (CRA-115).

A Crawfish project is the deploy / isolation / reproducibility unit. Like
Next.js, users do **not** hand-write a ``Containerfile``; ``craw build`` derives
one deterministically from the manifest (:class:`~crawfish.config.ProjectManifest`)
and the lockfile (``crawfish.lock``). The generated image installs the project
and its pinned dependencies, copies the project tree, and sets the entrypoint to
``craw run`` so the container *is* the runnable automation.

Triple duty (CRA-115): the container is the reproducibility unit (pinned deps),
the isolation boundary for host-side node code, and the on-prem delivery format.
Caveat: an in-container ``loop`` falls back to the CMA managed runtime unless a
local runtime is also packaged in the image.
"""

from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel, Field

from crawfish.config import ProjectManifest

__all__ = [
    "DEFAULT_PYTHON_VERSION",
    "BuildPlan",
    "generate_containerfile",
    "plan_build",
    "write_containerfile",
]

DEFAULT_PYTHON_VERSION = "3.11"

# Name of the lockfile copied into the image when present (CRA-115).
LOCKFILE_NAME = "crawfish.lock"


def _base_image(python_version: str) -> str:
    """Derive the deterministic base image tag for ``python_version`` (CRA-115)."""
    return f"python:{python_version}-slim"


def generate_containerfile(
    manifest: ProjectManifest,
    *,
    python_version: str = DEFAULT_PYTHON_VERSION,
    lock_present: bool = True,
) -> str:
    """Generate deterministic Containerfile text for ``manifest`` (CRA-115).

    The output installs dependencies (``pip install`` of the project, plus the
    pinned ``crawfish.lock`` when ``lock_present``), copies the project tree, and
    sets the entrypoint to ``craw run``. The string is stable for a given input
    so builds are reproducible.
    """
    base = _base_image(python_version)
    lines = [
        f"# Generated by craw build (CRA-115) for {manifest.name}:{manifest.version}.",
        "# Do not edit by hand; regenerate with `craw build`.",
        f"FROM {base}",
        "",
        "WORKDIR /app",
        "",
    ]
    if lock_present:
        lines += [
            f"# Pinned dependencies from {LOCKFILE_NAME} (reproducible build).",
            f"COPY {LOCKFILE_NAME} ./{LOCKFILE_NAME}",
            f"RUN pip install --no-cache-dir --requirement {LOCKFILE_NAME}",
            "",
        ]
    lines += [
        "# Copy the self-contained project and install crawfish + the project.",
        "COPY . .",
        "RUN pip install --no-cache-dir .",
        "",
        "# The container is the runnable automation.",
        'ENTRYPOINT ["craw", "run"]',
    ]
    return "\n".join(lines) + "\n"


class BuildPlan(BaseModel):
    """Summary of what ``craw build`` will produce for a project (CRA-115)."""

    image: str
    base_image: str
    python_version: str = DEFAULT_PYTHON_VERSION
    lock_present: bool = True
    steps: list[str] = Field(default_factory=list)


def plan_build(
    manifest: ProjectManifest,
    *,
    python_version: str = DEFAULT_PYTHON_VERSION,
    lock_present: bool = True,
) -> BuildPlan:
    """Build a :class:`BuildPlan` from ``manifest`` (CRA-115).

    The image name/tag is derived as ``name:version`` from the manifest.
    """
    steps = [
        f"FROM {_base_image(python_version)}",
        "WORKDIR /app",
    ]
    if lock_present:
        steps.append(f"pip install --requirement {LOCKFILE_NAME}")
    steps += [
        "COPY project tree",
        "pip install .",
        "ENTRYPOINT craw run",
    ]
    return BuildPlan(
        image=f"{manifest.name}:{manifest.version}",
        base_image=_base_image(python_version),
        python_version=python_version,
        lock_present=lock_present,
        steps=steps,
    )


def write_containerfile(
    manifest: ProjectManifest,
    dest: str | Path,
    *,
    python_version: str = DEFAULT_PYTHON_VERSION,
    lock_present: bool = True,
) -> Path:
    """Write the generated Containerfile to ``dest`` and return its path (CRA-115).

    If ``dest`` is a directory, the file is written as ``dest/Containerfile``.
    """
    path = Path(dest)
    if path.is_dir():
        path = path / "Containerfile"
    text = generate_containerfile(
        manifest, python_version=python_version, lock_present=lock_present
    )
    path.write_text(text)
    return path
